### PR TITLE
fix: detection status not being sent on iOS

### PR DESCRIPTION
**Pull request by alboiuvlad29**
Fixes [RND-108353](https://mews.myjetbrains.com/youtrack/agiles/88-200/current?issue=RND-108353)

### CODE REVIEW

**Review by Sevastyan — CHANGES_REQUESTED** [review]
Commit history is dirty.

And we don't use `master` branch. Currently `kiosk` is pointing to `55b10c77e1987caa9c6d0e50f82f3804c2d07868`, which is on `use-specific-version` branch. You can branch off of that branch.

**Comment by alboiuvlad29** [comment]
@Sevastyan I know we don't use master here as our reference, but let's change that and use the same review flow we have in other places. Currently it's very hard to track what changes have been made and which one's the latest branch that should be used in our apps. For example, you've worked on the nationality while I worked on this hotfix. Which one should merge the other's changes and update the kiosk version? I suggest (even with this dirty commit history for now) to push new fixes on master/main.

**Comment by Sevastyan** [comment]
@alboiuvlad29 I agree that it is a mess. But don't push anything to `master`. Let's create a branch off of `master`, e.g. `mews` and merge the latest reference that kiosk uses in production to it. And then, the additions should be diffed to `mews` branch.

**Comment by alboiuvlad29** [comment]
@Sevastyan Agreed. I thought when you add stuff to master it is being added to `MewsSystems/blinkid-flutter/master` not upstream `BlinkID/blinkid-flutter/master`. I will create another branch now, called main (not that happy with the old `master` notation).

**Comment by Sevastyan** [comment]
@alboiuvlad29

> I thought when you add stuff to master it is being added to MewsSystems/blinkid-flutter/master not upstream BlinkID/blinkid-flutter/master

This is a `MewsSystems/blinkid-flutter` repository. So, if anything that is added to `master` here is added here - not in an upstream `BlinkID/blinkid-flutter/master`.

I am aware of this purely political "master v. main" debate and have a strong preference towards `master`. Currently, there is `master` and `main` which is even more confusing. Please, make it something else than `main`, e.g. `mews`.

**Pull request closed without merging**
